### ISSUE TITLE
Build Errors in both Linux and Mac OS X Environements

### ISSUE THREAD

**Issue by sviyer** [facebookexperimental/RocketSpeed#1]
I cloned RocketSpeed in both Mac OS X (10.11.1) and Ubuntu (LTS 14.04) and I get identical errors:

Unable to find gflags/gflags.h

I made a quick hack to add the following in Makefile (Line 38)
PLATFORM_CXXFLAGS += -I./external/gflags/include

This fixed the build problem. 

However, I got errors in server/main.cc that GFLAGS is not defined. Again, I made a simple hack of 
#define GFLAGS gflags

[While grepping I saw GFLAGS = google, and since version 2.x, it should be gflags]

This fixed the error in server/main.cc

I then got an error in server/server.cc 
#ifndef GFLAGS
#error "gflags is required for rocketspeed"
#endif

I then added a global compilation flag -DGFLAGS=gflags (Again in makefile, same place as above) and I get tons of errors:
src/server/server.o: In function `__static_initialization_and_destruction_0':
/home/sviyer/code/mqtte/RocketSpeed/src/server/server.cc:38: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/home/sviyer/code/mqtte/RocketSpeed/src/server/server.cc:39: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/home/sviyer/code/mqtte/RocketSpeed/src/server/server.cc:42: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/home/sviyer/code/mqtte/RocketSpeed/src/server/server.cc:45: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/home/sviyer/code/mqtte/RocketSpeed/src/server/server.cc:48: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
src/server/server.o:/home/sviyer/code/mqtte/RocketSpeed/src/server/server.cc:52: more undefined references to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)' follow

Just wanted to check if it is building for everyone, or if I am the only one facing issues 

But the behavior is identical between Mac OS X and Ubuntu (Running using Parallels in the same machine)

**Comment by dyniusz** [comment]
Hi,
Please try to install gflags.
MacOS, depending on your pkg manager: 
brew install gflags 
sudo ports install gflags         

Ubuntu:
sudo yum install gflags

Let me know if that helped,
Marcin

**Comment by StanislavGlebik** [comment]
Hey. You should install gflags.

On Ubuntu try to run sudo apt-get install libgflags-dev, if it doesn't work, try this: http://askubuntu.com/questions/312173/installing-gflags-12-04

Also you can look at this page, it contains instructions to install gflags: https://github.com/facebook/rocksdb/blob/master/INSTALL.md

**Comment by sviyer** [comment]
Thanks @dyniusz , @StanislavGlebik ! 

I got past the gflags compilation issue (with some minor modification in the Makefile (in OS X)). I am getting linker errors in OS X and Linux. I'll update this thread once I am through with the build. (Looks like I need to install some additional modules)

Thanks again for the quick updates. 

Some updates:

<B>Mac OS X (10.11.1) <B>


With installing gflags from source and also using brew, I was still getting error <code>"Unable to include gflags/gflags.h" </code>

I found that gflags is installed in /usr/local/include which was not in the Include path list in makefile. I added <CODE> CXXFLAGS += -I/usr/local/include </CODE>  in the makefile. The compilation proceeds well after that. I am getting a couple of linker errors though:

<code>
Undefined symbols for architecture x86_64:
  "google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)", referenced from:
      __GLOBAL__sub_I_server.cc in server.o
      __GLOBAL__sub_I_logdevice.cc in logdevice.o
  "google::SetUsageMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      _main in main.o
  "google::ParseCommandLineFlags(int*, char***, bool)", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [rocketspeed] Error 1
</code>



<B>Ubuntu (LTS 14.04) <B>

I am getting linker errors here as well

<code>
/home/sviyer/code/RocketSpeed/build_tools/build_detect_platform: 186: /home/sviyer/code/RocketSpeed/build_tools/build_detect_platfor
m: DIRS+= src/logdevice: not found

/home/sviyer/code/RocketSpeed/build_tools/build_detect_platform: 338: /home/sviyer/code/RocketSpeed/build_tools/build_detect_platfor
m: JAVA_LDFLAGS+= -Wl,--no-whole-archive -L/jre/lib/amd64 -L/jre/lib/amd64/server -L/lib: not found

/home/sviyer/code/RocketSpeed/build_tools/build_detect_platform: 339: /home/sviyer/code/RocketSpeed/build_tools/build_detect_platfor
m: JAVA_LDFLAGS+= -Wl,--no-whole-archive -L/jre/lib/amd64 -ldl -lverify -ljava -ljvm: not found

/home/sviyer/code/RocketSpeed/build_tools/build_detect_platform: 186: /home/sviyer/code/RocketSpeed/build_tools/build_detect_platfor
m: DIRS+= src/logdevice: not found

/home/sviyer/code/RocketSpeed/build_tools/build_detect_platform: 338: /home/sviyer/code/RocketSpeed/build_tools/build_detect_platfor
m: JAVA_LDFLAGS+= -Wl,--no-whole-archive -L/jre/lib/amd64 -L/jre/lib/amd64/server -L/lib: not found
/home/sviyer/code/RocketSpeed/build_tools/build_detect_platform: 339: /home/sviyer/code/RocketSpeed/build_tools/build_detect_platfor

m: JAVA_LDFLAGS+= -Wl,--no-whole-archive -L/jre/lib/amd64 -ldl -lverify -ljava -ljvm: not found

ar: creating librocketspeed.a

src/server/logdevice.o: In function `construct<rocketspeed::LogDeviceLogRouter, long unsigned int&, long unsigned int&>':
/usr/include/c++/4.8/ext/new_allocator.h:120: undefined reference to `rocketspeed::LogDeviceLogRouter::LogDeviceLogRouter(unsigned l
ong, unsigned long)'

src/server/logdevice.o: In function `rocketspeed::CreateLogStorage(rocketspeed::Env*, std::shared_ptr<rocketspeed::Logger>)':

/home/sviyer/code/RocketSpeed/src/server/logdevice.cc:66: undefined reference to `rocketspeed::LogDeviceStorage::Create(std::string,
 std::string, std::string, std::chrono::duration<long, std::ratio<1l, 1000l> >, int, unsigned long, std::string, std::string, rocket
speed::Env*, std::shared_ptr<rocketspeed::Logger>, rocketspeed::LogDeviceStorage**)'

src/server/logdevice.o: In function `__shared_count<rocketspeed::LogDeviceStorage*>':
/usr/include/c++/4.8/bits/shared_ptr_base.h:456: undefined reference to `rocketspeed::LogDeviceStorage::~LogDeviceStorage()'
src/server/logdevice.o: In function `std::_Sp_counted_ptr<rocketspeed::LogDeviceStorage*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()'
:


/usr/include/c++/4.8/bits/shared_ptr_base.h:290: undefined reference to `rocketspeed::LogDeviceStorage::~LogDeviceStorage()'
collect2: error: ld returned 1 exit status
make: *** [rocketspeed] Error 1
</code>

**Comment by sviyer** [comment]
Update - Ubuntu Linux (LTS 14.04)

I had missed installing JRE in this VM (from the first linker message) - After installing OpenJDK6-JRE package, I got past the first linker error. Now looks like there is just one linker error pending. 

I'll provide an update once I have any.

<code>
src/server/logdevice.o: In function `construct<rocketspeed::LogDeviceLogRouter, long unsigned int&, long unsigned int&>':
/usr/include/c++/4.8/ext/new_allocator.h:120: undefined reference to `rocketspeed::LogDeviceLogRouter::LogDeviceLogRouter(unsigned long, unsigned long)'
src/server/logdevice.o: In function `rocketspeed::CreateLogStorage(rocketspeed::Env*, std::shared_ptr<rocketspeed::Logger>)':
/home/sviyer/code/RocketSpeed/src/server/logdevice.cc:66: undefined reference to `rocketspeed::LogDeviceStorage::Create(std::string, std::string, std::string, std::chrono::duration<long, std::ratio<1l, 1000l> >, int, unsigned long, std::string, std::string, rocketspeed::Env*, std::shared_ptr<rocketspeed::Logger>, rocketspeed::LogDeviceStorage**)'
src/server/logdevice.o: In function `__shared_count<rocketspeed::LogDeviceStorage*>':
/usr/include/c++/4.8/bits/shared_ptr_base.h:456: undefined reference to `rocketspeed::LogDeviceStorage::~LogDeviceStorage()'
src/server/logdevice.o: In function `std::_Sp_counted_ptr<rocketspeed::LogDeviceStorage*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
/usr/include/c++/4.8/bits/shared_ptr_base.h:290: undefined reference to `rocketspeed::LogDeviceStorage::~LogDeviceStorage()'
collect2: error: ld returned 1 exit status
</code>

**Comment by dhruba** [comment]
Are you running "make release"?

**Comment by sviyer** [comment]
@dhruba , I am running just <code> make clean </code> and <code> make </code>

<b> Mac OS X </b>

I get the following errors when I run <code> make release </code> 

find: src/java: No such file or directory
make[1]: [clean] Error 1 (ignored)

1 error generated.
make[1]: *** [src/tools/rocketbench/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [release] Error 2

<b> Ubuntu </b>

Getting too many errors when I do <code> make release </code>

Do you recommend I do make release? Or should I just stick to make?

PS: - I also tried branching out the last released version, and I get the same issues. May be some thing is messed up in my build environment. I'll recheck.

**Comment by dyniusz** [comment]
Hello,

Please edit RocketSpeed/build_tools/build_detect_platform file and change the 1st line
from: #!/bin/sh
to: #!/bin/bash

Before that I suggest to revert all the changes you have done to Makefiles and run make clean.
Please let us know if that helped.

**Comment by sviyer** [comment]
@dyniusz - I tried it out 

Good news first :+1: 

I was able to successfully build RocketSpeed in my VM Linux (Ubuntu) - Now I'll try get and end-to-end setup running tomorrow and update. 


<b> Mac OS X </b>
I got the unable to include <code> gflags/gflags.h </code>

I think the issue is in Mac OS X, the default install of gflags goes to /usr/local/include which is not included in the search path for the compiler by default

I am getting more gflags related issues with this change which I didn't have with sh (compared to bash)

I'll try other ways to build

<code>
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocketspeed.a(port_android.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocketspeed.a(rs_strlcpy.o) has no symbols
g++ -g -I/usr/local/include -Wall -Werror -Wshadow -Wconversion -Wno-sign-conversion -I. -I./include -std=c++11  -DROCKETSPEED_PLATFORM_POSIX  -Iexternal/libevent-2.0.21/include -Iexternal/libevent-2.0.21/macos -Iexternal -I external/djinni/support-lib/jni -Isrc/djinni/generated/c++ -DOS_MACOSX  -DROCKETSPEED_ATOMIC_PRESENT -DZLIB -DBZIP2 -I/include -I/include/linux   -DHAVE_JEMALLOC -O2 -fno-omit-frame-pointer -momit-leaf-frame-pointer -Woverloaded-virtual -Wnon-virtual-dtor -DOUTPUT_TEST_TIMES -c src/server/main.cc -o src/server/main.o 
src/server/main.cc:20:3: error: use of undeclared identifier 'GFLAGS'
  GFLAGS::SetUsageMessage(std::string("\nUSAGE:\n") + std::string(argv[0]) +
  ^
src/server/main.cc:22:3: error: use of undeclared identifier 'GFLAGS'
  GFLAGS::ParseCommandLineFlags(&argc, &argv, true);

</code>

I'll try to debug on why the build errors happen in Mac OS X. (Easier to work with me than the VM) - But I am super elated on getting the build up on Linux. 

Thanks a lot, guys!

**Comment by dyniusz** [comment]
@sviyer
The problem with symbols is similar to headers case. libgflags dir is not included in libraries paths during compilation - linking fails. There's a script in the repo build_tools/mac-install-gflags.sh to do the configuration for you. Since you have gflags already installed my advice is to execute only below calls:
```
# Add include/lib path for g++
echo 'export LIBRARY_PATH+=":/usr/local/lib"' >> ~/.bash_profile
echo 'export CPATH+=":/usr/local/include"' >> ~/.bash_profile
```

Note that this implicitly assumes your default shell to be bash.

**Comment by sviyer** [comment]
@dyniusz  

With the changes to .bash_profile, build works in Mac OS X as well. 

I'll try out the real messaging stuff now, and reach out if I need any help. 

This is my first time working with an Open Source project and coming back to C++ after a while in Python. 

Thanks for all the quick responses and support. 

[Since the default shell is bash in Mac OS X, adding these lines to the mac-install-gflags.sh should help newcomers as well]

I am marking the issue closed.

**Comment by dyniusz** [comment]
@sviyer
These 2 lines are in the mac-install-gflags.sh already. I've copy-pasted from the file.
#! line should be fixed though.
