### ISSUE TITLE
Rockerbench doesn't receive messages!

### ISSUE THREAD

**Issue by rezakarimii** [facebookexperimental/RocketSpeed#6]
When I run rocketbench --start_local_server on Ubuntu, it doesn't receive any messages.
I also used **-num_messages_to_receive**, but no chances either.

./rocketbench --start_local_server
Subscribing to topics... done
Publishing : 1000 messages.
Waiting for messages.
All 1000 messages published.4%)  received: 0/1000 (0.0%)  failed: 0
Time out awaiting messages. (1)

Results
Elapsed time: 8 sec
1000 publishes
1000 publishes acked
0 messages received

Messages failed to receive, expected 1000 found 0
0-999
Saved topic metadata into file ./RocketBenchProducer.dat

**Comment by fb-pja** [comment]
Hey, thanks for reporting. Could you pull latest and check if it works now? Seemed to be a SIOF issue with the namespace.

**Comment by rezakarimii** [comment]
Yes, it works now!
Thank you :+1:
